---
- name: Install erlang the dependency
  yum:
    name="{{ erlang_rpm_remote_url }}"
    state=present

- name: Install rabbitmq from remote URL
  yum:
    name="{{ rabbitmq_rpm_remote_url }}"
    state=present

- name: Ensure rabbitmq service is started
  service:
    name=rabbitmq-server
    state=started
    enabled=yes

- name: Enables the rabbitmq_management plugin
  rabbitmq_plugin:
    names=rabbitmq_management
    state=enabled

- name: Ensure rabbitmq user is created
  rabbitmq_user:
    user=admin
    password=admin
    vhost=/
    configure_priv=.*
    read_priv=.*
    write_priv=.*
    state=present
    tags=administrator

- name: Remove rabbitmq guest user
  rabbitmq_user:
    user=guest
    state=absent
